/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed": "#07006c",
        "on-tertiary-fixed": "#301400",
        "on-error-container": "#93000a",
        "on-surface-variant": "#464554",
        "on-surface": "#191c1d",
        "on-primary-container": "#fffbff",
        "on-secondary-container": "#fffbff",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed": "#0f0069",
        "on-background": "#191c1d",
        "background": "#f8f9fa",
        "primary": "#4648d4",
        "primary-fixed": "#e1e0ff",
        "primary-container": "#6063ee",
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#3323cc",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "outline": "#767586",
        "tertiary-container": "#b55d00",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#e2dfff",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "surface-container": "#edeeef",
        "tertiary": "#904900",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#c3c0ff",
        "outline-variant": "#c7c4d7",
        "surface-container-low": "#f3f4f5",
        "surface-tint": "#494bd6",
        "inverse-on-surface": "#f0f1f2",
        "secondary": "#4b41e1",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#703700",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-container": "#645efb",
        "inverse-primary": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdcc5",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb783"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "gutter": "24px",
        "md": "16px",
        "base": "4px",
        "margin-desktop": "32px",
        "sm": "8px",
        "margin-mobile": "16px",
        "max-width": "1440px",
        "xs": "4px",
        "xl": "32px"
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
